### ISSUE TITLE
Add release packages for Linux

### ISSUE THREAD

**Issue by rkm** [HicServices/BadMedicine.Dicom#1]
Just leaving this as a placeholder. Looks like we only build Windows binaries at the moment, and they don't look to be configured through Travis.

**Comment by tznind** [comment]
Yup we should figure out how to schedules this.  I think the binaries are signed by our UoD code signing cert in Jenkins.  @Tallmaris maybe we could look at moving all our FOSS deployment to use travis-ci?

**Comment by rkm** [comment]
Just an update - this may be a bit of a blocker for building the combined integration tests with IsIdentifiable. It's fairly easy to pull and extract an archive, but much more difficult and error-prone to dynamically pull a git repo & build the package from it.

**Comment by tznind** [comment]
Ok.  I am working on getting TypeGuesser deploying to nuget through travis-ci.  Once that is working I will expand it to the other repos.

**Comment by tznind** [comment]
This was created by Travis-CI :
https://github.com/HicServices/BadMedicine.Dicom/releases/tag/test

For some reason the job lists a failure state:

https://travis-ci.com/HicServices/BadMedicine.Dicom/jobs/280461420

But the files were generated correctly and theres no error message or stack trace so will just have to watch it for now.

**Comment by rkm** [comment]
There was a syntax error in the Travis config, fixed with https://github.com/HicServices/BadMedicine.Dicom/commit/8541ce23a53b8ddad10c1eb67a54c272bce7bce1. The build looks fine now.

**Comment by tznind** [comment]
Ok, since theres no features yet I won't push a full release, can you use this for now for any integration testing you are doing where you need to pull a binary? and we can update it to a full version later?

**Comment by rkm** [comment]
Sure, I think that's fine for now. Thanks

**Comment by tznind** [comment]
Figured out why the deploy section keeps crashing but the binaries still appear, it's because travis-ci.org is shipping the binary (and has the secure password) and then travis-ci.com version is bombing.  So the repo is currently building in both oops.
